export const RESET = "RESET";

export const SET_RIGHT_ARM_START = "SET_RIGHT_ARM";
export const SET_RIGHT_ARM_SUCCESS = "SET_RIGHT_ARM_SUCCESS";
export const SET_RIGHT_ARM_ERROR = "SET_RIGHT_ARM_ERROR";

export const GET_RIGHT_ARM_START = "GET_RIGHT_ARM";
export const GET_RIGHT_ARM_SUCCESS = "GET_RIGHT_ARM_SUCCESS";
export const GET_RIGHT_ARM_ERROR = "GET_RIGHT_ARM_ERROR";
